workspace:
  base: /app
  path: .

pipeline:
  verify:
    image: python:3.7
    commands:
      - pip install --upgrade pip setuptools wheel
      - pip install --no-cache-dir -r requirements.txt
      - pip install --no-cache-dir -r test-requirements.txt
      - pip install -e .
      - flake8
      - pytest -s --cov-config .coveragerc --cov=svc --cov-report term-missing svc/tests
